export type Exercise = {
  id: string
  name: string
  muscleGroups: string[]
  equipment: string
  injuryRisk: string[]
  alternatives: string[]
  instructions: string
}

export const EXERCISES: Exercise[] = [
  // CHEST
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'barbell',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['dumbbell_bench_press', 'cable_fly', 'push_up'],
    instructions: 'Lie on bench, grip bar slightly wider than shoulder-width, lower to chest then press up.',
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['barbell_bench_press', 'cable_fly', 'push_up'],
    instructions: 'Lie on bench holding dumbbells at chest level, press up and slightly inward.',
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['incline_barbell_press', 'cable_fly', 'push_up'],
    instructions: 'Set bench to 30-45°, press dumbbells from upper chest level upward.',
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    muscleGroups: ['chest'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['dumbbell_fly', 'push_up', 'dumbbell_bench_press'],
    instructions: 'Stand between cables set at chest height, bring handles together in an arc in front of you.',
  },
  {
    id: 'push_up',
    name: 'Push Up',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'bodyweight',
    injuryRisk: ['wrist', 'shoulder'],
    alternatives: ['dumbbell_bench_press', 'cable_fly'],
    instructions: 'Hands shoulder-width on floor, lower chest to ground then push back up.',
  },

  // BACK
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    injuryRisk: ['lower back'],
    alternatives: ['cable_row', 'dumbbell_row', 'lat_pulldown'],
    instructions: 'Hinge at hips, pull barbell to lower chest, keep back flat throughout.',
  },
  {
    id: 'cable_row',
    name: 'Cable Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['barbell_row', 'dumbbell_row', 'lat_pulldown'],
    instructions: 'Sit at cable machine, pull handle to lower abdomen, squeeze shoulder blades.',
  },
  {
    id: 'dumbbell_row',
    name: 'Dumbbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['lower back'],
    alternatives: ['cable_row', 'lat_pulldown'],
    instructions: 'Place one knee on bench, pull dumbbell to hip, keep elbow close to body.',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_row', 'pull_up', 'dumbbell_row'],
    instructions: 'Grip bar wider than shoulders, pull down to upper chest, lean back slightly.',
  },
  {
    id: 'pull_up',
    name: 'Pull Up',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['lat_pulldown', 'cable_row'],
    instructions: 'Hang from bar, pull until chin clears bar, lower with control.',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    muscleGroups: ['back', 'glutes', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['cable_row', 'romanian_deadlift', 'leg_press'],
    instructions: 'Bar over mid-foot, hinge and grip bar, drive hips forward to stand tall.',
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    muscleGroups: ['back', 'glutes', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['cable_row', 'dumbbell_row', 'leg_press'],
    instructions: 'Hold bar at hips, hinge forward keeping legs nearly straight, feel hamstring stretch.',
  },

  // SHOULDERS
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'barbell',
    injuryRisk: ['shoulder', 'neck'],
    alternatives: ['dumbbell_shoulder_press', 'lateral_raise', 'cable_lateral_raise'],
    instructions: 'Press barbell from shoulder height to overhead, keep core braced.',
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['overhead_press', 'lateral_raise'],
    instructions: 'Sit upright, press dumbbells from ear level to overhead, lower with control.',
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_lateral_raise', 'dumbbell_shoulder_press'],
    instructions: 'Stand with dumbbells at sides, raise to shoulder height with slight elbow bend.',
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['lateral_raise', 'dumbbell_shoulder_press'],
    instructions: 'Stand beside cable, pull handle out to side to shoulder height.',
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['lateral_raise', 'cable_row'],
    instructions: 'Set cable at head height, pull rope to face with elbows flared out.',
  },

  // BICEPS
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    injuryRisk: ['wrist', 'elbow'],
    alternatives: ['dumbbell_curl', 'cable_curl', 'hammer_curl'],
    instructions: 'Stand holding bar with underhand grip, curl to shoulder keeping elbows fixed.',
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['wrist'],
    alternatives: ['barbell_curl', 'cable_curl', 'hammer_curl'],
    instructions: 'Stand holding dumbbells, curl one or both to shoulders with supinated wrist.',
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    muscleGroups: ['biceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['dumbbell_curl', 'barbell_curl'],
    instructions: 'Stand at low cable, curl bar or handle to shoulder height keeping elbows back.',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['wrist'],
    alternatives: ['dumbbell_curl', 'cable_curl'],
    instructions: 'Hold dumbbells with neutral grip (thumbs up), curl to shoulder height.',
  },

  // TRICEPS
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['overhead_tricep_extension', 'dips', 'skull_crusher'],
    instructions: 'Stand at high cable, push bar down to full extension keeping elbows by sides.',
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['elbow', 'shoulder'],
    alternatives: ['tricep_pushdown', 'skull_crusher'],
    instructions: 'Hold dumbbell overhead with both hands, lower behind head then extend up.',
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    muscleGroups: ['triceps'],
    equipment: 'barbell',
    injuryRisk: ['elbow', 'shoulder'],
    alternatives: ['tricep_pushdown', 'overhead_tricep_extension'],
    instructions: 'Lie on bench, lower bar to forehead by bending elbows, then extend back up.',
  },
  {
    id: 'dips',
    name: 'Dips',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    equipment: 'bodyweight',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['tricep_pushdown', 'skull_crusher'],
    instructions: 'Hold parallel bars, lower body by bending elbows to 90°, push back up.',
  },

  // LEGS
  {
    id: 'barbell_squat',
    name: 'Barbell Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'barbell',
    injuryRisk: ['knee', 'lower back', 'hip'],
    alternatives: ['leg_press', 'goblet_squat', 'split_squat'],
    instructions: 'Bar on upper traps, squat down until thighs are parallel, drive through heels.',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'leg press machine',
    injuryRisk: ['knee', 'lower back'],
    alternatives: ['goblet_squat', 'split_squat', 'leg_extension'],
    instructions: 'Sit in machine, feet hip-width, push platform away and return with control.',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'dumbbell',
    injuryRisk: ['knee'],
    alternatives: ['leg_press', 'split_squat'],
    instructions: 'Hold dumbbell at chest, squat deep keeping elbows inside knees.',
  },
  {
    id: 'split_squat',
    name: 'Bulgarian Split Squat',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'dumbbell',
    injuryRisk: ['knee', 'hip'],
    alternatives: ['leg_press', 'goblet_squat', 'leg_extension'],
    instructions: 'Rear foot elevated on bench, lower front knee toward floor, drive up through heel.',
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    muscleGroups: ['legs'],
    equipment: 'leg press machine',
    injuryRisk: ['knee'],
    alternatives: ['goblet_squat', 'split_squat'],
    instructions: 'Sit in machine, extend legs to straight, lower with control.',
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    muscleGroups: ['legs'],
    equipment: 'leg press machine',
    injuryRisk: ['knee'],
    alternatives: ['romanian_deadlift', 'split_squat'],
    instructions: 'Lie face down in machine, curl heels toward glutes, lower with control.',
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    muscleGroups: ['legs'],
    equipment: 'bodyweight',
    injuryRisk: [],
    alternatives: ['leg_press'],
    instructions: 'Stand on edge of step, raise up onto toes, lower heel below step level.',
  },

  // GLUTES
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['glute_bridge', 'split_squat', 'cable_kickback'],
    instructions: 'Upper back on bench, bar on hips, drive hips to full extension and squeeze.',
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['hip_thrust', 'cable_kickback'],
    instructions: 'Lie on back, feet flat, drive hips up squeezing glutes at top.',
  },
  {
    id: 'cable_kickback',
    name: 'Cable Kickback',
    muscleGroups: ['glutes'],
    equipment: 'cable machine',
    injuryRisk: ['hip'],
    alternatives: ['glute_bridge', 'hip_thrust'],
    instructions: 'Stand at low cable with ankle strap, kick leg straight back squeezing glute.',
  },

  // CORE
  {
    id: 'plank',
    name: 'Plank',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['dead_bug', 'cable_crunch'],
    instructions: 'Hold push-up position on forearms, keep body in straight line for time.',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    muscleGroups: ['core'],
    equipment: 'cable machine',
    injuryRisk: ['lower back', 'neck'],
    alternatives: ['plank', 'dead_bug'],
    instructions: 'Kneel at high cable, hold rope at head, crunch down bringing elbows to knees.',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: [],
    alternatives: ['plank', 'cable_crunch'],
    instructions: 'Lie on back, extend opposite arm and leg while keeping lower back pressed to floor.',
  },

  // CHEST — expanded
  {
    id: 'decline_bench_press',
    name: 'Decline Bench Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'barbell',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['dumbbell_bench_press', 'cable_fly', 'dips'],
    instructions: 'Set bench to 15-30° decline, press bar from lower chest up.',
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck / Machine Fly',
    muscleGroups: ['chest'],
    equipment: 'machine',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_fly', 'dumbbell_fly'],
    instructions: 'Sit at pec deck machine, bring arms together in front of chest in a hugging motion.',
  },
  {
    id: 'dumbbell_fly',
    name: 'Dumbbell Fly',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_fly', 'pec_deck'],
    instructions: 'Lie on bench, arms out wide with slight bend, bring dumbbells together above chest.',
  },
  {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    muscleGroups: ['chest'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_fly', 'pec_deck', 'dumbbell_fly'],
    instructions: 'Stand between high cables, bring handles down and together in front of lower chest.',
  },
  {
    id: 'chest_dips',
    name: 'Chest Dips',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'bodyweight',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['dips', 'dumbbell_bench_press', 'cable_fly'],
    instructions: 'Lean forward on parallel bars to target chest, lower until elbows are at 90°.',
  },
  {
    id: 'incline_barbell_press',
    name: 'Incline Barbell Press',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'barbell',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['incline_dumbbell_press', 'cable_fly'],
    instructions: 'Set bench to 30-45°, press barbell from upper chest upward.',
  },

  // BACK — expanded
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable machine',
    injuryRisk: ['lower back'],
    alternatives: ['cable_row', 'dumbbell_row', 'barbell_row'],
    instructions: 'Sit at cable row station, pull handle to abdomen keeping back straight.',
  },
  {
    id: 'chest_supported_row',
    name: 'Chest Supported Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
    injuryRisk: [],
    alternatives: ['dumbbell_row', 'cable_row'],
    instructions: 'Lie face down on incline bench, row dumbbells up towards hips.',
  },
  {
    id: 'tbar_row',
    name: 'T-Bar Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    injuryRisk: ['lower back'],
    alternatives: ['barbell_row', 'cable_row', 'dumbbell_row'],
    instructions: 'Straddle loaded bar end, grip handle attachment, row bar to chest.',
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Straight Arm Pulldown',
    muscleGroups: ['back'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['lat_pulldown', 'pull_up'],
    instructions: 'Stand at high cable, arms straight, pull bar down to thighs using lats only.',
  },
  {
    id: 'hyperextension',
    name: 'Back Extension / Hyperextension',
    muscleGroups: ['back', 'glutes'],
    equipment: 'machine',
    injuryRisk: ['lower back'],
    alternatives: ['romanian_deadlift', 'glute_bridge'],
    instructions: 'Lie face down on hyperextension bench, lower torso then raise back to parallel.',
  },
  {
    id: 'single_arm_cable_row',
    name: 'Single Arm Cable Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['dumbbell_row', 'cable_row'],
    instructions: 'Stand at cable, pull single handle to hip rotating trunk slightly.',
  },

  // SHOULDERS — expanded
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['dumbbell_shoulder_press', 'overhead_press'],
    instructions: 'Start with palms facing you, rotate outward as you press overhead.',
  },
  {
    id: 'front_raise',
    name: 'Front Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['lateral_raise', 'cable_lateral_raise'],
    instructions: 'Stand holding dumbbells, raise arms straight to shoulder height in front.',
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'dumbbell',
    injuryRisk: [],
    alternatives: ['face_pull', 'cable_lateral_raise'],
    instructions: 'Hinge forward, raise dumbbells out to sides in reverse fly motion.',
  },
  {
    id: 'cable_face_pull',
    name: 'Cable Face Pull',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['face_pull', 'rear_delt_fly'],
    instructions: 'Pull rope attachment to face height, elbows high, flaring out to sides.',
  },
  {
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'machine',
    injuryRisk: ['shoulder'],
    alternatives: ['dumbbell_shoulder_press', 'overhead_press'],
    instructions: 'Sit at shoulder press machine, press handles overhead.',
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    muscleGroups: ['shoulders', 'chest', 'triceps'],
    equipment: 'barbell',
    injuryRisk: ['shoulder'],
    alternatives: ['dumbbell_shoulder_press', 'arnold_press'],
    instructions: 'Hold end of loaded barbell at shoulder height, press up and forward.',
  },

  // BICEPS — expanded
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['elbow'],
    alternatives: ['dumbbell_curl', 'cable_curl'],
    instructions: 'Lie on incline bench, let arms hang, curl dumbbells with full stretch.',
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['elbow'],
    alternatives: ['dumbbell_curl', 'cable_curl'],
    instructions: 'Sit with elbow braced on inner thigh, curl dumbbell to shoulder.',
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    injuryRisk: ['elbow'],
    alternatives: ['barbell_curl', 'cable_curl'],
    instructions: 'Rest arms on preacher bench pad, curl bar up from full extension.',
  },
  {
    id: 'cable_hammer_curl',
    name: 'Cable Hammer Curl',
    muscleGroups: ['biceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['hammer_curl', 'cable_curl'],
    instructions: 'Stand at low cable with rope, curl up with neutral grip (palms facing).',
  },
  {
    id: 'reverse_curl',
    name: 'Reverse Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    injuryRisk: ['elbow', 'wrist'],
    alternatives: ['hammer_curl', 'cable_curl'],
    instructions: 'Hold bar with overhand grip, curl up — targets brachialis and forearms.',
  },

  // TRICEPS — expanded
  {
    id: 'close_grip_bench',
    name: 'Close Grip Bench Press',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'barbell',
    injuryRisk: ['elbow', 'wrist'],
    alternatives: ['tricep_pushdown', 'skull_crusher'],
    instructions: 'Grip bar shoulder-width, lower to chest and press — elbows stay tucked in.',
  },
  {
    id: 'cable_tricep_kickback',
    name: 'Cable Tricep Kickback',
    muscleGroups: ['triceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['tricep_pushdown', 'overhead_tricep_extension'],
    instructions: 'Hinge forward at cable, extend arm fully back to target long tricep head.',
  },
  {
    id: 'bench_dip',
    name: 'Bench Dip',
    muscleGroups: ['triceps'],
    equipment: 'bodyweight',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['dips', 'tricep_pushdown'],
    instructions: 'Hands on bench behind you, lower body by bending elbows, press back up.',
  },
  {
    id: 'rope_pushdown',
    name: 'Rope Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['tricep_pushdown', 'cable_tricep_kickback'],
    instructions: 'Use rope attachment at high cable, push down and flare rope out at bottom.',
  },

  // LEGS — expanded
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'machine',
    injuryRisk: ['knee', 'lower back'],
    alternatives: ['leg_press', 'barbell_squat'],
    instructions: 'Stand in hack squat machine, squat down to 90° and drive through heels.',
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'barbell',
    injuryRisk: ['knee', 'lower back', 'wrist'],
    alternatives: ['barbell_squat', 'goblet_squat'],
    instructions: 'Bar rests on front deltoids, elbows high, squat keeping torso very upright.',
  },
  {
    id: 'walking_lunge',
    name: 'Walking Lunge',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'dumbbell',
    injuryRisk: ['knee', 'hip'],
    alternatives: ['split_squat', 'goblet_squat'],
    instructions: 'Step forward into lunge, alternate legs walking forward across floor.',
  },
  {
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    muscleGroups: ['legs'],
    equipment: 'machine',
    injuryRisk: ['knee'],
    alternatives: ['leg_curl', 'romanian_deadlift'],
    instructions: 'Sit at leg curl machine, curl legs under seat towards glutes.',
  },
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    muscleGroups: ['legs'],
    equipment: 'machine',
    injuryRisk: [],
    alternatives: ['calf_raise'],
    instructions: 'Stand on calf raise machine, raise up onto toes with full range of motion.',
  },
  {
    id: 'sumo_squat',
    name: 'Sumo Squat',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'dumbbell',
    injuryRisk: ['knee', 'hip'],
    alternatives: ['goblet_squat', 'split_squat'],
    instructions: 'Stand wide with toes turned out, hold dumbbell at chest, squat down.',
  },
  {
    id: 'box_squat',
    name: 'Box Squat',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'barbell',
    injuryRisk: ['knee', 'lower back'],
    alternatives: ['barbell_squat', 'hack_squat'],
    instructions: 'Squat back and down onto a box, pause briefly, then drive back up.',
  },
  {
    id: 'leg_press_wide',
    name: 'Wide Stance Leg Press',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'leg press machine',
    injuryRisk: ['knee', 'lower back'],
    alternatives: ['leg_press', 'sumo_squat'],
    instructions: 'Leg press with feet placed wide and high to bias glutes and hamstrings.',
  },

  // GLUTES — expanded
  {
    id: 'single_leg_hip_thrust',
    name: 'Single Leg Hip Thrust',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['hip_thrust', 'glute_bridge'],
    instructions: 'One foot on floor, other extended, drive hips up squeezing glute.',
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    muscleGroups: ['glutes', 'legs', 'back'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['romanian_deadlift', 'hip_thrust'],
    instructions: 'Wide stance with toes out, grip inside legs, drive hips forward to stand.',
  },
  {
    id: 'cable_pull_through',
    name: 'Cable Pull Through',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'cable machine',
    injuryRisk: ['lower back'],
    alternatives: ['hip_thrust', 'romanian_deadlift'],
    instructions: 'Stand facing away from low cable, hinge forward gripping rope through legs, drive hips forward.',
  },
  {
    id: 'donkey_kickback',
    name: 'Donkey Kickback',
    muscleGroups: ['glutes'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['cable_kickback', 'glute_bridge'],
    instructions: 'On hands and knees, kick one leg straight back and up squeezing glute at top.',
  },

  // CORE — expanded
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['cable_crunch', 'plank'],
    instructions: 'Sit with knees bent, lean back slightly, rotate torso side to side.',
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back', 'neck'],
    alternatives: ['cable_crunch', 'russian_twist'],
    instructions: 'Lie on back, alternate bringing elbow to opposite knee in cycling motion.',
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['cable_crunch', 'dead_bug'],
    instructions: 'Hang from pull-up bar, raise legs straight or with knees bent to waist height.',
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['plank', 'dead_bug'],
    instructions: 'Kneel with ab wheel, roll forward maintaining rigid core, roll back to start.',
  },
  {
    id: 'side_plank',
    name: 'Side Plank',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['plank', 'dead_bug'],
    instructions: 'Support body on one forearm and foot, keep hips raised in straight line.',
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    muscleGroups: ['core'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['plank', 'dead_bug'],
    instructions: 'Stand side-on to cable, hold handle at chest, press straight out resisting rotation.',
  },
  {
    id: 'cable_woodchop',
    name: 'Cable Woodchop',
    muscleGroups: ['core'],
    equipment: 'cable machine',
    injuryRisk: ['lower back'],
    alternatives: ['russian_twist', 'pallof_press'],
    instructions: 'Pull cable from high to low across body in diagonal chopping motion.',
  },

  // LEGS — functional
  {
    id: 'step_up',
    name: 'Step Up',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'dumbbell',
    injuryRisk: ['knee', 'hip'],
    alternatives: ['split_squat', 'walking_lunge'],
    instructions: 'Hold dumbbells at sides, step onto a box one foot at a time, step back down.',
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Curl',
    muscleGroups: ['legs'],
    equipment: 'bodyweight',
    injuryRisk: ['knee'],
    alternatives: ['leg_curl', 'romanian_deadlift'],
    instructions: 'Anchor feet under pad, lower torso slowly toward floor using hamstrings, catch yourself, return.',
  },
  {
    id: 'sissy_squat',
    name: 'Sissy Squat',
    muscleGroups: ['legs'],
    equipment: 'bodyweight',
    injuryRisk: ['knee'],
    alternatives: ['leg_extension', 'goblet_squat'],
    instructions: 'Hold support, lean back as you lower knees toward floor with heels raised, return under control.',
  },

  // BACK — functional
  {
    id: 'meadows_row',
    name: 'Meadows Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    injuryRisk: ['lower back'],
    alternatives: ['dumbbell_row', 'single_arm_cable_row'],
    instructions: 'Stand at end of landmine barbell, row handle to hip with one hand using overhand grip.',
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    muscleGroups: ['back', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['romanian_deadlift', 'hyperextension'],
    instructions: 'Bar on upper traps, hinge forward at hips keeping back flat until torso is near parallel, return.',
  },

  // BICEPS — functional
  {
    id: 'spider_curl',
    name: 'Spider Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['elbow'],
    alternatives: ['incline_dumbbell_curl', 'concentration_curl'],
    instructions: 'Lie chest-down on incline bench, curl dumbbells from hanging position with full contraction.',
  },

  // TRICEPS — functional
  {
    id: 'tate_press',
    name: 'Tate Press',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['elbow', 'shoulder'],
    alternatives: ['skull_crusher', 'overhead_tricep_extension'],
    instructions: 'Lie on bench, dumbbells at chest pointing up, flare elbows out and lower ends to chest, press back.',
  },

  // GLUTES — functional
  {
    id: 'frog_pump',
    name: 'Frog Pump',
    muscleGroups: ['glutes'],
    equipment: 'bodyweight',
    injuryRisk: [],
    alternatives: ['glute_bridge', 'donkey_kickback'],
    instructions: 'Lie on back with soles of feet together, knees flared out, pump hips up squeezing glutes.',
  },
  {
    id: 'reverse_hyper',
    name: 'Reverse Hyperextension',
    muscleGroups: ['glutes', 'back'],
    equipment: 'machine',
    injuryRisk: ['lower back'],
    alternatives: ['hyperextension', 'glute_bridge'],
    instructions: 'Lie face down on reverse hyper machine, swing legs up and back squeezing glutes at top.',
  },

  // CORE — functional
  {
    id: 'hollow_body_hold',
    name: 'Hollow Body Hold',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['dead_bug', 'plank'],
    instructions: 'Lie on back, press lower back into floor, extend arms and legs low, hold the hollow position.',
  },
  {
    id: 'copenhagen_plank',
    name: 'Copenhagen Plank',
    muscleGroups: ['core', 'legs'],
    equipment: 'bodyweight',
    injuryRisk: ['hip'],
    alternatives: ['side_plank', 'pallof_press'],
    instructions: 'Side plank with top foot resting on a bench, bottom leg off the floor, hold for time.',
  },
  {
    id: 'dragon_flag',
    name: 'Dragon Flag',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['hanging_leg_raise', 'ab_wheel_rollout'],
    instructions: 'Lie on bench gripping behind head, raise body in rigid plank from shoulders, lower with control.',
  },
]

export const EXERCISE_MAP = Object.fromEntries(EXERCISES.map((e) => [e.id, e]))

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_MAP[id]
}

export const MUSCLE_GROUP_COLORS: Record<string, string> = {
  chest: 'bg-blue-500/20 text-blue-400',
  back: 'bg-purple-500/20 text-purple-400',
  shoulders: 'bg-yellow-500/20 text-yellow-400',
  biceps: 'bg-pink-500/20 text-pink-400',
  triceps: 'bg-orange-500/20 text-orange-400',
  legs: 'bg-red-500/20 text-red-400',
  glutes: 'bg-rose-500/20 text-rose-400',
  core: 'bg-green-500/20 text-green-400',
}
