export type Exercise = {
  id: string
  name: string
  muscleGroups: string[]
  equipment: string
  injuryRisk: string[]
  alternatives: string[]
  instructions: string
}

export const EXERCISES: Exercise[] = [
  // CHEST
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'barbell',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['dumbbell_bench_press', 'cable_fly', 'push_up'],
    instructions: 'Lie on bench, grip bar slightly wider than shoulder-width, lower to chest then press up.',
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['barbell_bench_press', 'cable_fly', 'push_up'],
    instructions: 'Lie on bench holding dumbbells at chest level, press up and slightly inward.',
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['incline_barbell_press', 'cable_fly', 'push_up'],
    instructions: 'Set bench to 30-45°, press dumbbells from upper chest level upward.',
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    muscleGroups: ['chest'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['dumbbell_fly', 'push_up', 'dumbbell_bench_press'],
    instructions: 'Stand between cables set at chest height, bring handles together in an arc in front of you.',
  },
  {
    id: 'push_up',
    name: 'Push Up',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'bodyweight',
    injuryRisk: ['wrist', 'shoulder'],
    alternatives: ['dumbbell_bench_press', 'cable_fly'],
    instructions: 'Hands shoulder-width on floor, lower chest to ground then push back up.',
  },

  // BACK
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    injuryRisk: ['lower back'],
    alternatives: ['cable_row', 'dumbbell_row', 'lat_pulldown'],
    instructions: 'Hinge at hips, pull barbell to lower chest, keep back flat throughout.',
  },
  {
    id: 'cable_row',
    name: 'Cable Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['barbell_row', 'dumbbell_row', 'lat_pulldown'],
    instructions: 'Sit at cable machine, pull handle to lower abdomen, squeeze shoulder blades.',
  },
  {
    id: 'dumbbell_row',
    name: 'Dumbbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['lower back'],
    alternatives: ['cable_row', 'lat_pulldown'],
    instructions: 'Place one knee on bench, pull dumbbell to hip, keep elbow close to body.',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_row', 'pull_up', 'dumbbell_row'],
    instructions: 'Grip bar wider than shoulders, pull down to upper chest, lean back slightly.',
  },
  {
    id: 'pull_up',
    name: 'Pull Up',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['lat_pulldown', 'cable_row'],
    instructions: 'Hang from bar, pull until chin clears bar, lower with control.',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    muscleGroups: ['back', 'glutes', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['cable_row', 'romanian_deadlift', 'leg_press'],
    instructions: 'Bar over mid-foot, hinge and grip bar, drive hips forward to stand tall.',
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    muscleGroups: ['back', 'glutes', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['cable_row', 'dumbbell_row', 'leg_press'],
    instructions: 'Hold bar at hips, hinge forward keeping legs nearly straight, feel hamstring stretch.',
  },

  // SHOULDERS
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'barbell',
    injuryRisk: ['shoulder', 'neck'],
    alternatives: ['dumbbell_shoulder_press', 'lateral_raise', 'cable_lateral_raise'],
    instructions: 'Press barbell from shoulder height to overhead, keep core braced.',
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['overhead_press', 'lateral_raise'],
    instructions: 'Sit upright, press dumbbells from ear level to overhead, lower with control.',
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    injuryRisk: ['shoulder'],
    alternatives: ['cable_lateral_raise', 'dumbbell_shoulder_press'],
    instructions: 'Stand with dumbbells at sides, raise to shoulder height with slight elbow bend.',
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'cable machine',
    injuryRisk: ['shoulder'],
    alternatives: ['lateral_raise', 'dumbbell_shoulder_press'],
    instructions: 'Stand beside cable, pull handle out to side to shoulder height.',
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'cable machine',
    injuryRisk: [],
    alternatives: ['lateral_raise', 'cable_row'],
    instructions: 'Set cable at head height, pull rope to face with elbows flared out.',
  },

  // BICEPS
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    injuryRisk: ['wrist', 'elbow'],
    alternatives: ['dumbbell_curl', 'cable_curl', 'hammer_curl'],
    instructions: 'Stand holding bar with underhand grip, curl to shoulder keeping elbows fixed.',
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['wrist'],
    alternatives: ['barbell_curl', 'cable_curl', 'hammer_curl'],
    instructions: 'Stand holding dumbbells, curl one or both to shoulders with supinated wrist.',
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    muscleGroups: ['biceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['dumbbell_curl', 'barbell_curl'],
    instructions: 'Stand at low cable, curl bar or handle to shoulder height keeping elbows back.',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    injuryRisk: ['wrist'],
    alternatives: ['dumbbell_curl', 'cable_curl'],
    instructions: 'Hold dumbbells with neutral grip (thumbs up), curl to shoulder height.',
  },

  // TRICEPS
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'cable machine',
    injuryRisk: ['elbow'],
    alternatives: ['overhead_tricep_extension', 'dips', 'skull_crusher'],
    instructions: 'Stand at high cable, push bar down to full extension keeping elbows by sides.',
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    injuryRisk: ['elbow', 'shoulder'],
    alternatives: ['tricep_pushdown', 'skull_crusher'],
    instructions: 'Hold dumbbell overhead with both hands, lower behind head then extend up.',
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    muscleGroups: ['triceps'],
    equipment: 'barbell',
    injuryRisk: ['elbow', 'shoulder'],
    alternatives: ['tricep_pushdown', 'overhead_tricep_extension'],
    instructions: 'Lie on bench, lower bar to forehead by bending elbows, then extend back up.',
  },
  {
    id: 'dips',
    name: 'Dips',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    equipment: 'bodyweight',
    injuryRisk: ['shoulder', 'wrist'],
    alternatives: ['tricep_pushdown', 'skull_crusher'],
    instructions: 'Hold parallel bars, lower body by bending elbows to 90°, push back up.',
  },

  // LEGS
  {
    id: 'barbell_squat',
    name: 'Barbell Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'barbell',
    injuryRisk: ['knee', 'lower back', 'hip'],
    alternatives: ['leg_press', 'goblet_squat', 'split_squat'],
    instructions: 'Bar on upper traps, squat down until thighs are parallel, drive through heels.',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'leg press machine',
    injuryRisk: ['knee', 'lower back'],
    alternatives: ['goblet_squat', 'split_squat', 'leg_extension'],
    instructions: 'Sit in machine, feet hip-width, push platform away and return with control.',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipment: 'dumbbell',
    injuryRisk: ['knee'],
    alternatives: ['leg_press', 'split_squat'],
    instructions: 'Hold dumbbell at chest, squat deep keeping elbows inside knees.',
  },
  {
    id: 'split_squat',
    name: 'Bulgarian Split Squat',
    muscleGroups: ['legs', 'glutes'],
    equipment: 'dumbbell',
    injuryRisk: ['knee', 'hip'],
    alternatives: ['leg_press', 'goblet_squat', 'leg_extension'],
    instructions: 'Rear foot elevated on bench, lower front knee toward floor, drive up through heel.',
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    muscleGroups: ['legs'],
    equipment: 'leg press machine',
    injuryRisk: ['knee'],
    alternatives: ['goblet_squat', 'split_squat'],
    instructions: 'Sit in machine, extend legs to straight, lower with control.',
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    muscleGroups: ['legs'],
    equipment: 'leg press machine',
    injuryRisk: ['knee'],
    alternatives: ['romanian_deadlift', 'split_squat'],
    instructions: 'Lie face down in machine, curl heels toward glutes, lower with control.',
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    muscleGroups: ['legs'],
    equipment: 'bodyweight',
    injuryRisk: [],
    alternatives: ['leg_press'],
    instructions: 'Stand on edge of step, raise up onto toes, lower heel below step level.',
  },

  // GLUTES
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'barbell',
    injuryRisk: ['lower back', 'hip'],
    alternatives: ['glute_bridge', 'split_squat', 'cable_kickback'],
    instructions: 'Upper back on bench, bar on hips, drive hips to full extension and squeeze.',
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    muscleGroups: ['glutes', 'legs'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['hip_thrust', 'cable_kickback'],
    instructions: 'Lie on back, feet flat, drive hips up squeezing glutes at top.',
  },
  {
    id: 'cable_kickback',
    name: 'Cable Kickback',
    muscleGroups: ['glutes'],
    equipment: 'cable machine',
    injuryRisk: ['hip'],
    alternatives: ['glute_bridge', 'hip_thrust'],
    instructions: 'Stand at low cable with ankle strap, kick leg straight back squeezing glute.',
  },

  // CORE
  {
    id: 'plank',
    name: 'Plank',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: ['lower back'],
    alternatives: ['dead_bug', 'cable_crunch'],
    instructions: 'Hold push-up position on forearms, keep body in straight line for time.',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    muscleGroups: ['core'],
    equipment: 'cable machine',
    injuryRisk: ['lower back', 'neck'],
    alternatives: ['plank', 'dead_bug'],
    instructions: 'Kneel at high cable, hold rope at head, crunch down bringing elbows to knees.',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
    injuryRisk: [],
    alternatives: ['plank', 'cable_crunch'],
    instructions: 'Lie on back, extend opposite arm and leg while keeping lower back pressed to floor.',
  },
]

export const EXERCISE_MAP = Object.fromEntries(EXERCISES.map((e) => [e.id, e]))

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_MAP[id]
}

export const MUSCLE_GROUP_COLORS: Record<string, string> = {
  chest: 'bg-blue-500/20 text-blue-400',
  back: 'bg-purple-500/20 text-purple-400',
  shoulders: 'bg-yellow-500/20 text-yellow-400',
  biceps: 'bg-pink-500/20 text-pink-400',
  triceps: 'bg-orange-500/20 text-orange-400',
  legs: 'bg-red-500/20 text-red-400',
  glutes: 'bg-rose-500/20 text-rose-400',
  core: 'bg-green-500/20 text-green-400',
}
